# Generated by Django 5.0.6 on 2024-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='myportfolio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='employee_portfolio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
