# Generated by Django 5.0.6 on 2024-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0002_employee_myportfolio_pdf_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images'),
        ),
    ]
