# Generated by Django 5.0.6 on 2024-06-09 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='myportfolio_pdf',
        ),
        migrations.AddField(
            model_name='employee',
            name='myportfolio',
            field=models.FileField(blank=True, null=True, upload_to='employee_portfolio/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
