# Generated by Django 5.0.6 on 2024-06-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0005_employeehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='emloyee_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
