# Generated by Django 5.0.6 on 2024-06-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0006_employeehistory_emloyee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='operation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
