# Generated by Django 5.0.6 on 2024-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesummary',
            name='invoice_no',
            field=models.IntegerField(default=0),
        ),
    ]
