# Generated by Django 5.0.6 on 2024-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0002_invoicesummary_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='itemnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
